export const POST_PRODUCT_REQUEST = "POST_PRODUCT_REQUEST"
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAIL = "POST_PRODUCT_FAIL"

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"


export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS"
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL"
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET"

