export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"
export const USER_SIGNOUT = "USER_SIGNOUT"

export const USER_CHANGE_EMAIL_REQUEST = "USER_CHANGE_EMAIL_REQUEST"
export const USER_CHANGE_EMAIL_SUCCESS = "USER_CHANGE_EMAIL_SUCCESS"
export const USER_CHANGE_EMAIL_FAIL = "USER_CHANGE_EMAIL_FAIL"

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST"
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS"
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL"

export const USER_VALIDATE_OTP_REQUEST = "USER_VALIDATE_OTP_REQUEST"
export const USER_VALIDATE_OTP_SUCCESS = "USER_VALIDATE_OTP_SUCCESS"
export const USER_VALIDATE_OTP_FAIL = "USER_VALIDATE_OTP_FAIL"

export const USER_VALIDATE_PASS_OTP_REQUEST = "USER_VALIDATE_PASS_OTP_REQUEST"
export const USER_VALIDATE_PASS_OTP_SUCCESS = "USER_VALIDATE_PASS_OTP_SUCCESS"
export const USER_VALIDATE_PASS_OTP_FAIL = "USER_VALIDATE_PASS_OTP_FAIL"

export const USER_CHANGE_DETAILS_REQUEST = "USER_CHANGE_DETAILS_REQUEST"
export const USER_CHANGE_DETAILS_SUCCESS = "USER_CHANGE_DETAILS_SUCCESS"
export const USER_CHANGE_DETAILS_FAIL = "USER_CHANGE_DETAILS_FAIL"

